### ISSUE TITLE
Add ArchiSteamFarm in FreeStuffBot environment

### ISSUE THREAD

**Issue by Glaived** [FreeStuffBot/discord#1]
**Describe the solution you'd like**
Adding [ArchiSteamFarm (ASF)](https://github.com/JustArchiNET/ArchiSteamFarm/blob/master/README.md) to FreeStuff would allow ASF users to get the games directly via ASF, without going through the traditional method (SteamClient/Browser => Connection => (2FA) => Add the game to the account)

This would only be available if I play a game on Steam.

Here is an example of FreeStuff display with an option enabled for ASF display:

![image](https://user-images.githubusercontent.com/1835170/93211885-22261c00-f762-11ea-8243-261ff4388cbe.png)

**Comment by Maanex** [comment]
Hey there, this feature has been suggested before. Since we didn't want to include this in all themes because only a small percentage of our users can tage advantage of it, we decided to add a new theme that should satisfy your needs. This theme was released and announced a while back but didn't make it to the current website yet since we're already working on an entirely new website.
![image](https://user-images.githubusercontent.com/23345879/93251303-4bf83680-f794-11ea-9831-0b3a55bfcad3.png)
I'm going to close this issue now, feel free to re-open if you want to add to the conversation.
